### ISSUE TITLE
Loot structures missing

### ISSUE THREAD

**Issue by AllieWade** [Lythom/capsule#2]
Tested in a new Minecraft instance, created and installed through the Twitch launcher, with only Capsule and JEI.

Minecraft 1.12.2
forge-14.23.1.2558
Capsule-1.12.2-1.5.39.jar
jei_1.12.2-4.8.5.132.jar

Loot capsules are found as expected, but none of the loot structures are generating. Any loot structure received has its name ("One Use "Small Villager House" Capsule"), is designed by ?, and has a size of -1 x -1 x -1. Deploying them shows a 1x1x1 deployment box and does not generate a structure.

A directory structure for capsules is present in config (/config/capsule/loot/common etc, /config/capsule/rewards) but there are no files in the directories. There is no /structures directory or /assets directory.

Sorry for the trouble! I really love this mod, and I thank you for making it.

**Comment by Lythom** [comment]
This bug is related with resource ids required to be lowercase since 1.12. It will be fixed in the next release (probably this month).

Regarding the folders, the assets/ folder is located in the mod jar file so it's normal it doesn't appear. The folder in the config are there so that users and modpack makers can easily add new structures in. It's a bit confusing so I plan to keep only /config/capsule/loots as unique place for loots, and copy default structures there during the first lunch. Hopefully it will be more intuitive to understand and use.

Thank you for the report and cheers ! Both really helps =)

**Comment by AllieWade** [comment]
Sweet! Thanks for the information, that makes sense. Live long & prosper!

**Comment by Lythom** [comment]
Now fixed in latests versions 1.12.2, 1.11.2 and 1.10.2 and published at https://minecraft.curseforge.com/projects/capsule.

Fixed by commit ef081615a823a8adb3bfb0e052333be730a2f1f0

As planned, structure files will now be located in config/capsule/loot an no more in the jar. The folder will be filled with the default templates when first created.

When upgrading from an previous version, in `config/capsule.cfg`, you will have to remove all lines that begins with `asset/` from the loot directories (or remove the file to generate a new default config) AND remove folder `/config/capsule/loot`. Default loots will be re-generated there.
