### ISSUE TITLE
Immersive Engineering Pumps not capsuling/blueprinting properly.

### ISSUE THREAD

**Issue by NukerNoah** [Lythom/capsule#31]
Minecraft: 1.12.2
Version: Capsule 1.12.2-3.3.11, Immersive Engineering 0.12-98
Pack: Manufactio 1.33b

Immersive Engineering pumps will capture and blueprint, but will not deny the ability to rotate the capsule.
This is an issue as when the capsule is rotated, the faces of the pump will not rotate. This typically results in a non-functioning pump.

The North face of a pump will always face North, even when the capsule is rotated 180 such that it should now face South.

**Comment by Lythom** [comment]
Thanks for reporting ! Sorry for the delay also.

Here is some insight about the issue:
Blueprint beeing able to rotate is a fundamental statement, it means a block that cannot rotate should never be allowed in a blueprint. 
To ensure this, tile-entities (special blocks) that are allowed to rotate and be in blueprints are whitelisted in `config/capsule/blueprint_whitelist.json`, this is not the case by default for IE pumps so I assume it was added by the pack maker.
As such I might not be able fix the issue directly, here are some options : 
- have immersive engineering dev make the pump block rotatable in structure blocks (can be tested using vanilla structure blocks creating a pump template and then loading it with various rotations configurations),
- have the mod-pack creator find an other way to give un-rotatable capsule (ie. linked or one-use capsule instead of blueprints), but it might not fit the experience he/she is looking for,
- have capsule implement an exception for this specific block, but it's a never ending task I don't want to take, I'm complying to the vanille structure blocks system precisely so that I any mod ensuring compatibility with vanilla structure block will work with capsules.

**Comment by Lythom** [comment]
I'm closing the issue but still open to discussion about it!
