### ISSUE TITLE
immersive engineering wire coils are not captured

### ISSUE THREAD

**Issue by thibaut-fagart** [Lythom/capsule#43]
i captured a multiblock structure (advanced bio gen from modularmachinery, in manufactio modpack), i had added wire connectors and relays on it, that were restored properly when deploying the capsule.

However 
- the wires connecting connectors/relays that are part of the captured area (used a 7*7*7 capsule and the multiblock with connectors was 5*5) were removed when captured but not restored on deploy.
- the same happened for the wires that were not completely contained in the captured volume but this is more understandable

**Comment by Lythom** [comment]
A bit late to answer sorry!
I assume the wire connectors or from immersive engineering (if not feel free to replace "immersive engineering" in the answer by the related mod, it should work the same)

This is a known incompatibility (https://github.com/Lythom/capsule/wiki/Known-incompatibilities), it's because wires works using absolute coordinates (world positions) rather that relative coordinates (relative to one another). So it means moving hem correctly would require a very specific implementation (which I prefer to avoid) for immersive engineering. I prefer to stay true to a vision where anything compatible with vanilla structure block system will work with capsule.

As is, wires don't work in vanilla structure blocks (if you duplicate a wire connection the spawned one won't have the wire working if positioned anywhere else the capture position). You might want to ask immersive engineering mod dev to comply with vanilla structure blocks mechanic (ability to save something, then to load it elsewhere). Anything compatible with this mechanics will work smoothly with capsules (and if not I'll make sure it does).
