### ISSUE TITLE
IE blueprints

### ISSUE THREAD

**Issue by Filostorm** [Lythom/capsule#48]
Is there any way for the default capsule blueprints to recognize ore Dictionary specifically for the steel blocks?￼￼

When attempting to fill them with thermal blocks it's needed to chisel them into the IE version first currently

**Comment by Lythom** [comment]
The thing is: 
- the steel blocks item creates different steel blocks in the world, so they are not the same thing,
- a recipe can declare to accept any steel_block or a mod-specific steel_block when declared, but from a specific steel_block it is not possible to generalize a "category compatible" item, only the exact item that matches the block.

So there is a by-design approach which make generalization of the problem not possible because the structures are defined by specific blocks, not recipes. 

Only a specific solution would work: it would be possible to add a capsule dedicated ore-dictionary. it would be tedious to fill and be used only for specific cases like the one you describe but would not work for everything.

Would that fit your need ? Also, what version of minecraft / capsule are having that need for?

**Comment by Filostorm** [comment]
Capsule-1.12.2-3.4.58.jar
For Minecraft version 1.12.2

I see what you're saying, can't just go around substituting different blocks and expect them to still work.

It seems like the capsule dedicated ore-dictionary would work, its really only for the IE multiblocks that can accept any version of the block to form.

**Comment by Lythom** [comment]
Thanks !
I'm not sure yet I'll backport the feature to 1.12, the forge support is over for this version but given the few changes on the capsule blueprint system between 1.12 and 1.16 I'll give it a try !
I created an issue to track the feature here: https://github.com/Lythom/capsule/issues/50
I'm closing this issue to track the evolution on #50, feel free to comment there to specify your need if it doesn't match.

**Comment by Filostorm** [comment]
That sounds awesome! Thanks for a great mod btw, it makes building a lot easier
