### ISSUE TITLE
[Question] Movement of Capsules from one world to another

### ISSUE THREAD

**Issue by savosdarkran** [Lythom/capsule#5]
Hello,

I was wondering if there was a way to move a structure from one save to another?

I moved:
<worldfolder>/playerdata/playeruuid.dat
<worldfolder>/structures/capsule/*
<worldfolder>/data/capsuleData.dat
to the new world, but it doesn't seem to be working.

**Comment by savosdarkran** [comment]
I see in the code "templates".  I will check what commands I have available and investigate this further on my end.

**Comment by Lythom** [comment]
Hello !

The easiest way to keep track of which capsule holds which content while moving the capsules from a world to another is to follow those steps :    
1. For each capsule, while holding the capsule in hand, use the command [/capsule fromHeldCapsule [name]](https://github.com/Lythom/capsule/wiki/Commands#fromheldcapsule). This will create a file in <instance>/config/capsule/rewards/.
2. Copy all files from <instance>/config/capsule/rewards/* to <newInstance>/config/capsule/rewards/.
3. For each capsule, use [/capsule fromExistingReward [name]](https://github.com/Lythom/capsule/wiki/Commands#fromexistingreward). Autocompletion is available to quickly get the names.

This will give you one-use capsules of your structures. There is currently no way to convert it easily in a standard capsule, the steps would be : put a capture base, deploy the one-use capsule on top of it, capture the area using a capsule with enough room.

Skipping step 1. and using files from <worldsave>/structures/capsule/* directly at step 2. would also work, but the capsule being named "c-username-id", it's not easy to know what the content is for each capsule. Since you already copied those file, you should be able to use directly step 3. for each capsule to get them all.

There is currently no implemented way to bulk copy all the capsules from the mod commands, your try to move both /playerdata/playeruuid.dat, /structures/capsule/*, and /data/capsuleData.dat is a good idea and might have worked. I'm not sure why it didn't work.

I added a "Add Bulk export / import command" to my todo list for capsule, but I can't give any delay for this.

**Comment by Lythom** [comment]
Updated recommanded steps to migrate (easier), no evolution in the mod itself is planned about the migration from world to world.
