### ISSUE TITLE
Crash caused by invalid resource path to "starter_house_of_the_hidden_barrel-0.schematics" and others. Happens every time i start a new world or join one.

### ISSUE THREAD

**Issue by JetpackRescue** [Lythom/capsule#61]
Here's 2 crash logs, adding capsul to my custom modpack causes a crash every time i try to create a new world or join that world.

Crash number 1
https://pastebin.com/aSF895n5

Crash number 2
https://pastebin.com/PbD6Bzri

1.16.5

**Comment by Lythom** [comment]
I've been away for some time, sorry for late answer !

I've got a similar issue reported with the following conclusion by the bug reporter :

> Found the problem, its on forge 1.16.5 - 36.2.23 for MultiMC and GDLauncher, industrial Agriculture setup phase fails but pack loads, while creating a new world apparently something happens between the capsule starting capsule and the staring gear trying to be given to the player and industrial IAP registry going through world setup and where finding all the seeds and compats for mystical agriculture’s that it crashes, like if it was overloading the process 
> It doesn’t matter if it a non new world either, so it happens during those stages
> Doesn’t happen on forge 36.2.26 though from what I have seen

So the issue was related by a conflict or other mod crash in a specific version of forge. You might want to try updating forge to latest version and see if there are errors from other mods.

Anyway It's not ok for capsule to crash, I'll update the mod so that it logs an errors but doesn't crash the client in such a case.

**Comment by Lythom** [comment]
Added a fix to prevent crash, released in 1.16.5-5.0.77+
https://www.curseforge.com/minecraft/mc-mods/capsule/files

Closing the issue for now but feel free to reopen if you fail to load your starter capsules.
