### ISSUE TITLE
1.16.5 Capsules not working on Topography Skylands world type

### ISSUE THREAD

**Issue by AnimeniacYuuto** [Lythom/capsule#67]
I get a Capsules can't be used here, it might be a protected area when trying to place a capsule in a Skylands World from topography, tried teleporting 1000 blocks away but the issue persists

**Comment by Lythom** [comment]
I suspect this is a height problem (given the "skyland" name of the world). Capsules are hard coded to prevent capture / deploy above a certain height, because it causes an irreverisble loss when trying to deploy above the height limit (255). 
Since I coded this, height limit is now flexible by world so I'll see if I can find a smarter way to do it, which should solve the issue.
Not sure when I'll get to this snce I still have to finish porting 1.18, but then I'll take a deeper look at it !

**Comment by AnimeniacYuuto** [comment]
Maybe, the average terrain height is around 150~

**Comment by Lythom** [comment]
Fixed in version 5.0.87.
There was a calculation error with both world height and capsule position 🙃 
Available on curseforge: https://www.curseforge.com/minecraft/mc-mods/capsule/files/3809557
