### ISSUE TITLE
Getting a Crash To Do With Water Usage?

### ISSUE THREAD

**Issue by Boolyman** [Lythom/capsule#7]
Players are crashing, log says something about users underwater.

https://pastebin.com/5K71HmdP

**Comment by Lythom** [comment]
Thanks for the report, I'll been checking this by the end of the week.

**Comment by Lythom** [comment]
Could reproduce the issue : the game would crash when the capsule is thrown by non-player entity (ex: dropper or dispenser). 

This regression was introduced with the water update :    
- issue is now fixed in version 1.12.2-3.1.69
- earlier versions are not affected (< 1.12.2-3.1.63)

1.12.2-3.1.69 is currently being uploaded, will close the issue once it is available.

**Comment by Lythom** [comment]
Now available at https://minecraft.curseforge.com/projects/capsule.
