### ISSUE TITLE
Capsules made from structures with air blocks will delete surrounding blocks.

### ISSUE THREAD

**Issue by TeetoKaziim** [Lythom/capsule#8]
I have a number of capsules for multiblock machines. One such machine looks like this:

![image](https://user-images.githubusercontent.com/25490944/44674792-3c162a00-a9f4-11e8-8ed9-34d58f88c75d.png)

If I deploy it like so:

![image](https://user-images.githubusercontent.com/25490944/44674837-5a7c2580-a9f4-11e8-98d1-a1e8d9ad2d80.png)

It will delete the sandstone/stonebrick blocks that fall inside the structure's area, rather than telling me those blocks are in the way:

![image](https://user-images.githubusercontent.com/25490944/44674878-7ed80200-a9f4-11e8-9605-8a63d4b34cdf.png)

I haven't tried it, but I imagine this can be prevented by /fill ing some structure voids into the air spaces before saving the structures, but I thought it bore mentioning. (Or, editing my existing .nbt files to change out the minecraft:air for minecraft:structure_void)

**Comment by Lythom** [comment]
Hi !
Thanks for taking the time to fill an issue.

This is not the usual behaviour : `minecraft:air` blocks that are inside the structure should not override anything (ever). On deploy, The existing non-blocking blocks inside the structure zone are saved, if they have not change they are left as-is when the capsule is undeployed.

I've successfully tested a similar case as yours with vanilla blocks using Capsule 3.1.69 and Forge 14.23.1.2555, the basic use case is working as expected.

I see some possible explanations for this to happen :    
1. There is an exception thrown (a code error) when deploying which causes the capsule mod to try rollbacking the deployment, and the rollback don't work as planned. In this case, you should see an error stack in the minecraft logs just after the deployment.
2. Since the machine is a multiblock, is this possible that the machine is "assembling" itself just after being deployed and removes the blocks in range but not being part of the multiblock ? This could be verified by trying the same deployment with plain blocks (ie. dirt) having the shape of the multiblock. If it works with dirt instead of the machine then we'll have to check more into the capsule / multiblock machine interaction to figure out. 

If the same issue is reproduced with dirt blocks instead of the machine, then I'll probably need to run the whole pack to be able to reproduce the issue since it could be some incompatibility with any the pack mod, (ie. a core mod that changes structure blocks behavior).

Feel free to ping me on discord for live support (Lythom#1893).

**Comment by Lythom** [comment]
Closing due to issue being inactive and problem can't be reproduced using capsule alone. Please reopen if the problem persist and you need assistance.
